; This file was auto-generated by drush make
core = 6.x

api = 2
projects[drupal][version] = "6.x"

; Modules
projects[admin_menu][version] = "3.0-alpha4"
projects[ubercart][version] = "2.11"
projects[uc_discounts_alt][version] = "2.4"
projects[cck][version] = "2.9"
projects[date][version] = "2.9"
projects[devel][version] = "1.27"
projects[filefield][version] = "3.10"
projects[imageapi][version] = "1.10"
projects[imagecache][version] = "2.0-rc1"
projects[imagefield][version] = "3.10"
projects[jquery_plugin][version] = "1.10"
projects[jquery_ui][version] = "1.5"
projects[jquery_update][version] = "2.0-alpha1"
projects[token][version] = "1.19"
projects[uc_coupon][version] = "1.7"
projects[uc_generate][version] = "1.0"
projects[uc_node_checkout][version] = "2.0-beta8"
projects[uc_who_bought_what][version] = "2.13"